# Agrega aqui el wallpaper final cuando el proyecto tenga assets propios.
# Ejemplo:
# preload = ~/Pictures/hypr_edition-wallpaper.png
# wallpaper = ,~/Pictures/hypr_edition-wallpaper.png
splash = false
