font_family JetBrainsMono Nerd Font
font_size 11.0

background #181825
foreground #cdd6f4
selection_background #585b70
selection_foreground #cdd6f4

cursor #f5e0dc
url_color #89b4fa

window_padding_width 8
confirm_os_window_close 0
